config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: 'static_pages#help'
  get "/about", to: 'static_pages#about'
  get "/contact", to: 'static_pages#contact'
  get "/signup", to: 'users#new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do 
    # the member method arranges for the routes to respond to URLs containing the user id
    member do 
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "email address not found"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "cant be empty")
      render 'edit', status: :unprocessable_entity
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "password has been reset"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # confirms a valid user
  def valid_user
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # checks expiration of reset token
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "password reset has expired"
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, url: password_reset_path(params[:id])) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= hidden_field_tag :email, @user.email %> <!-- This should be inside the form_with block -->
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>

            <%= f.submit "update password", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "forgot password") %>
<h1>Forgot password</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%# Because @password_reset doesn't correspond to an Active Record object, form_with won't automatically create a URL for it. By passing the :password_reset symbol and an explicit URL, we give Rails the information it needs to create the form %>
        <%= form_with(url: password_resets_path, scope: :password_reset) do  |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>