config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: 'static_pages#help'
  get "/about", to: 'static_pages#about'
  get "/contact", to: 'static_pages#contact'
  get "/signup", to: 'users#new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do 
    # the member method arranges for the routes to respond to URLs containing the user id
    member do 
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "Sample App", root_path, id: "logo" %>
        <nav>
            <div class="navbar-header">
                <button id="hamburger" type="button" class="navbar-toggle collapsed">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
             </div>
            <ul id="navbar-menu"
                class="nav navbar-nav navbar-right collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home",  root_path %></li>
                        <li><%= link_to "Help",  help_path %></li>
                        <% if logged_in? %>
                            <li><%= link_to "Users", users_path %></li>
                            <li class="dropdown">
                                <a href="#" id="account" class="dropdown-toggle">
                                    Account <b class="caret"></b>
                                </a>
                                <ul id="dropdown-menu" class="dropdown-menu">
                                    <li><%= link_to "Profile", current_user %></li>
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li>
                                        <%= link_to "Log out", logout_path, data: { "turbo-method": :delete } %>
                                    </li>
                                </ul>
                            </li>
                        <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% # the code below is using the application_helper %>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#-{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>